### ISSUE TITLE
Always getting loaded-context

### ISSUE THREAD

**Issue by diegosucaria** [okteto/kubernetes-context#6]
Hi there!

Thanks for the extension!!  I'm having a problem...  I installed it and it says "loaded-context" only. if I click it, the dropdown only shows one entry which says "loaded-context" too.

I have several contexts on my .kube/config file and the KUBECONFIG variable is exported correctly on the .bashrc 

Any ideas about what could be going on? or how can I debug it?

Thanks!!!

**Comment by diegosucaria** [comment]
Ok, something weird happened. After a reboot of the linux machine on wich vscode is running, now the context is loading properly

**Comment by rberrelleza** [comment]
thanks for updating us @diegosucaria . The plugin loads kubeconfig from either the KUBECONFIG envvar, or the default location $HOME/.kube/config. Maybe the env var got overwritten or something?
